name: Deploy to VPS

on:
  push:
    branches:
      - main  # Ganti ke 'master' kalau branch-mu bukan 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /path/to/odoo_project
            git pull origin main
            docker compose restart
